apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-cbc
  region: ap-southeast-1

managedNodeGroups:
- name: m1
  instanceType: m5.large
  labels: { role: web }
  desiredCapacity: 2
  privateNetworking: true
