apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: ap-southeast-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      ap-southeast-1a:
        id: subnet-077903fe6af074f97 
      ap-southeast-1b:
        id: subnet-0b75adbd28edfda59 


managedNodeGroups:
- name: m1
  instanceType: m5.large
  labels: { role: web }
  desiredCapacity: 2
  privateNetworking: true
