apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster-cbc
  region: ap-southeast-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      ap-southeast-1a:
        id: subnet-0a7c019b390586252
      ap-southeast-1b:
        id: subnet-02f459413f19ca4a9


managedNodeGroups:
- name: m1
  instanceType: m5.large
  labels: { role: web }
  desiredCapacity: 2
  privateNetworking: true
